### ISSUE TITLE
Невозможно зайти по адресу указному в документации

### ISSUE THREAD

**Issue by VegasChickiChicki** [Edw125/TestParser#2]
После запуска докера не получается подключиться по http://127.0.0.1:8000/, похоже приложение не запускается или не прокидывается из докера наружу.

**Comment by Edw125** [comment]
Пофиксил. Адрес работает по 0.0.0.0:8000

**Comment by VegasChickiChicki** [comment]
Теперь все работает, но по адресу http://127.0.0.1:8000/ :)
